spring:
  application:
    name: @project.artifactId@
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/example
    username: user
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /spring-boot-demo

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
    default-models-expand-depth: 0
    doc-expansion: none
    tags-sorter: alpha
  writer-with-default-pretty-printer: true